Repository BenjaminKnol/Challenge2019, pull requests merged in 2020-01, with the labels that each got.

#35 Fixing translate and spelling errors
  front_end_laravel/birdstay/resources/views/birds/create.blade.php
  front_end_laravel/birdstay/resources/views/birds/edit.blade.php
  front_end_laravel/birdstay/resources/views/birds/index.blade.php
Labels: bug

#34 Move layout.blade.php to views\layouts folder
  front_end_laravel/birdstay/resources/views/birds/create.blade.php
  front_end_laravel/birdstay/resources/views/birds/edit.blade.php
  front_end_laravel/birdstay/resources/views/birds/index.blade.php
  front_end_laravel/birdstay/resources/views/layouts/layout.blade.php
  front_end_laravel/birdstay/resources/views/locations/index.blade.php
  front_end_laravel/birdstay/resources/views/locations/show.blade.php
  front_end_laravel/birdstay/resources/views/pages/contact.blade.php
Labels: enhancement

#36 Update googlmapper.php
  front_end_laravel/birdstay/config/googlmapper.php
Labels: bug

#38 Merge branch 'pageHeight'
  front_end_laravel/birdstay/resources/views/layouts/layout.blade.php
Labels: enhancement

#47 Aad update
  javaCode/paho/src/main/java/MQTT.java
  javaCode/paho/src/main/java/Main.java
  javaCode/paho/src/main/java/PostgreSQL.java
Labels: enhancement

#48 Add logos
  docs/logo/dief.png
  docs/logo/dief_nacht.png
  docs/logo/eend.png
Labels: documentation

#49 Update layout.blade.php
  front_end_laravel/birdstay/resources/views/layouts/layout.blade.php
Labels: bug

#53 Send email notifications
  front_end_laravel/birdstay/composer.json
  front_end_laravel/birdstay/composer.lock
Labels: enhancement

#55 Update services.php
  front_end_laravel/birdstay/config/services.php
Labels: enhancement

#54 set up email-notifications when a bird goes missing
  front_end_laravel/birdstay/app/Http/Controllers/BirdController.php
  front_end_laravel/birdstay/app/Notifications/BirdMissing.php
Labels: enhancement
